sections = [
    [
        "Credits:",
        "Lead Developer - Frost Falcon",
        "Custom Sprites - Ninja Fish",
        "New Gen Pokemon Sprites - The Smogon Sprite Project, Moon Black 2, and HG-Engine",
        "Coding Assistance and Design Feedback - Various people in the Kingdom of DS Rom Hacking Discord",
    ],
    [
        "What is Infinite Black 2?",
        "Infinite Black 2 started development in 2021 with a simple premise: ",
        "To add variety such that each attempt at a nuzlocke would feel like a new experience.",
        "",
        "Initially, this was done by adding more Pokemon to the encounter pools and making minor balance adjustments and fixes to various Pokemon.",
        "Major trainer battles were also revamped to make the game more difficult, which adds a greater emphasis on team building.",
        "These also happened to be the only changes I knew how to make at the time, as it was my first time making a rom hack.",
        "",
        "Over time, the scope of these changes expanded as I learned what's possible with rom hacking. In fact, this hack was the driving force",
        "behind the creation of Frost's Gen 5 Rom Editor, one of the biggest tools in gen 5 rom hack development, and conversely, the research",
        "and development from those tools informs what I can add back to the rom hack. For example, when I developed a tool for editing Pokemon",
        "sprites, I got to rework some Pokemon's designs with much more creativity, and when I learned how to edit the game's code to add new",
        "moves and abilities, I started making a lot of those.",
        "",
        "What you'll notice, though, is that this hack has a complex blend of new concepts and things that are intentionally kept vanilla-like.",
        "I like many things about the vanilla game, and I think the most defining aspects, such as strong Pokemon, mechanics, and even the story,",
        "should be kept intact. Meanwhile, the things I do like to change are the things that are typically made redundant or unviable by",
        "those strong aspects. For example, Sandslash couldn't keep up with the many powerful ground types in the game, so it got changed.",
        "However, instead of just buffing it to compete directly, I gave it a new typing so that it could fill a unique role without",
        "drastically changing its power level.",
        "",
        "With this hack, I have a distinct way of deciding what changes should be made, with the main goal being to add variety within the",
        "vanilla environment. I'm not one to change things just for the sake of changing them, nor do I treat any vanilla content as perfect design,",
        "and I also never look to other hacks to decide what works best for my hack. I believe every idea, both new and old, should be evaluated",
        "for how it affects the game as a whole, and how it suits the creative vision. The good stuff is kept while the bad stuff gets changed.",
        "If I were to describe exactly how \"vanilla\" this hack is, it would be \"cookies and cream\" as you'll find changes everywhere",
        "that affect the overall flavor, but never enough to overshadow the vanilla flavor completely.",
        "",
        "About the difficulty:",
        "I want to make it clear that this is not a difficulty hack in the same vein as many of the popular ones you see online.",
        "While it may share many traits, and difficulty does play a role in this hack, the difference is that this hack is not designed to be",
        "a massive challenge above all else. I value the replayability and gamefeel at a casual to mid level of play, and the difficulty is",
        "just high enough to suit that. The variety does, however, facilitate challenge runs very well such as nuzlockes and monotype runs,",
        "so if you're a skilled player expecting a greater challenge, you should adjust the rules to suit your needs.",
        "",
        "Where this hack really shines is when you get to experiment with the new options that it provides. I wanted to create an",
        "environment with endless possibilities for creative team building, and with each update, the possibilities expand even more.",
        "I choose to use the term \"update,\" such as update 28, instead of \"version,\" such as version 1.0, to further convey this idea.",
        "There is no \"completed\" state for this hack. The game will always be effectively complete, but each update simply adds more on top.",
        "What this means is anyone can join in and play the hack at any time while updates give a reason to come back and explore more.",
        "Having played it countless times over hundreds of hours, I can confidently say that there's always something new to find, which",
        "is what's kept me coming back to develop it all this time.",
        //"Coincidentally, you'll notice this shows a lot of similarities with a group of \"Difficulty\" rom hacks like Radical Red and Blaze Black.",
        //"Unfortunately, this has led to a lot of confusion over why certain decisions are made, as those hacks get a lot more attention,",
        //"and their players have expectations for the design and intended playstyle which I personally find unreasonable.",
        //"These expectations are why I've changed my design goals to focus more on original, but still Vanilla-like, concepts,",
        //"and why I've explained these goals here with the hopes of creating a more clear niche for players who can enjoy my unique style."
    ],
    //[
    //    "Who is this hack for?",
    //    "I think this is an important aspect to bring up first, as there's a substantial group of players",
    //    "who will misinterpret it as a \"Difficulty\" hack, or \"Kaizo\" as I prefer to call it.",
    //    "",
    //    "Where Kaizo, from its inception with Super Mario World, is defined by intentionally unfair difficulty that forces",
    //    "the player to master every aspect of the game with little to no assistance, often requiring tools like damage calculators",
    //    "that make the game less fun for casual players and viewers, this hack aims for a more moderate difficulty level",
    //    "that allows mid level players to improve over time and showcase their ingenuity.",
    //    "",
    //    "Where this becomes a problem is when some players see Kaizo as the only style that matters and either neglect worse players",
    //    "or demand that the game be changed to accomodate them. (Both of which I've seen before with this hack and the community in general)",
    //    "With that said, let me be very clear that features like damage calculators and infinite rare candies will NOT be provided,",
    //    "as I believe they harm the enjoyment of casual level play. The reasons for this will be explained later on this page.",
    //    "",
    //    "Ultimately, I made this hack for myself so I can open it up in my free time and keep playing it without getting bored of the content.",
    //    "I'm far from the most skilled player, but part of that is because I prefer to play in the ways I find fun rather than what's optimal.",
    //    "I design a lot of the game with that playstyle in mind. In addition to nuzlockes, this leniency and difficulty level lends itself",
    //    "well to other types of challenge runs, like monotype and single team runs, that can take advantage of the encounter variety and balance.",
    //],
    //[
    //    "How I make changes",
    //    "As mentioned before, this hack started with simple changes to each Pokemon's base attributes, but these changes expanded as I learned",
    //    "what's possible in rom hacking. In fact, this hack was the driving force behind the development of Frost's Gen 5 Rom Editor,",
    //    "one of the biggest tools in gen 5 rom hack development, and conversely, the research and development from these tools",
    //    "informs what I can add back to the rom hack. For example, when I developed a tool for importing Pokemon sprites, I got to",
    //    "rework some Pokemon's designs with much more creativity, and when I learned how to edit the game's code to add new abilities",
    //    "and move behaviors, I started adding a lot more of those. The same goes for features like new story content too.",
    //    "",
    //    "Still, with all this power, I make it a point to retain the vanilla feel of the game. What do I mean by that?",
    //    "Well, I like the vanilla game. I like the way it handles strategy and power scaling, the way it lets you use any Pokemon if you",
    //    "know how to use it well, and I also like rewarding players for their past experience with the base game's mechanics.",
    //    "I think the most defining aspects should still be recognizable while the weaker and underexplored aspects are the ones",
    //    "that should be improved upon. If I were to describe exactly how \"vanilla\" this hack is, it would be cookies and cream.",
    //    "New and modified content is scattered all the game throughout, but not enough to overshadow vanilla content completely.",
    //    "",
    //    "Most of the new moves and abilities are what I would call \"new versions of existing concepts.\"",
    //    "Centrifuge is like Drizzle, but for gravity. Grass Cloak is like Rain Dish, but for sun. Fly Trap is like Water Absorb, but for bug moves.",
    //    "Adding things this way ensures that their power level doesn't deviate too much, and the player already has an idea of how to use them.",
    //    "It's also important that new features don't overshadow existing features. In the case of new moves, they will typically have a",
    //    "gimmick that synergizes with a particular strategy or Pokemon, but they won't completely outclass moves that those Pokemon normally use.",
    //    "",
    //    "The main story of the game is completely unchanged. Any new areas or cutscenes are optional and mainly serve to fill in gaps.",
    //    "I prefer not to remove anything that players may want to engage with, such as Pokestar Studios or the battle facilities,",
    //    "even if I don't use them myself.",
    //    "",
    //    "When it comes to Pokemon, many stand outs remain strong with very few changes. If you liked Excadrill and Darmanitan, for example,",
    //    "you can expect them to work the same here, but the stronger metagame surrounding them will require them to be used more carefully.",
    //    "The two biggest contributors to a Pokemon being changed are competition with similar Pokemon, and a desire to explore strategies",
    //    "that don't yet exist. A good example of this Sandslash, who wasn't necessarily weak but was severely overshadowed by the abundance",
    //    "of strong physical ground types. (Excadrill, Hippowdon, Marowak, and Gliscor to name a few) In this case, there's very little",
    //    "opportunity for Sandslash to compete on its own without an unreasonable amount of buffs that would then make those other",
    //    "Pokemon obsolete instead. So instead of buffing it directly, I redesigned it as a grass/ground type, giving it unique attributes",
    //    "that no other ground type could replicate without drastically changing its power level within the rest of the metagame.",
    //    "",
    //    "Some Pokemon do need significant buffs to become relevant, such as Lumineon and Magcargo who went from almost useless to",
    //    "metagame staples, but these are rare cases, and they are closely analyzed to see how they compare to other Pokemon and",
    //    "how they affect the rest of the metagame. In Lumineon's case, its main role is as a support, which I believe is allowed",
    //    "to be strong as it gives other Pokemon opportunities to shine instead of taking their opportunities away.",
    //    "",
    //    "Sometimes I decide that I want to add Pokemon from later generations into the game, but due to technical limitations,",
    //    "I have to replace existing Pokemon to do this. Since this means I have limited slots, in addition to the amount of work that",
    //    "goes into making these Pokemon look good, I have to choose these new Pokemon carefully. Generally, how much I like a Pokemon",
    //    "does play a part, (i.e. why I chose Decidueye over Chesnaught) but I also try to pick Pokemon that have something unique",
    //    "to offer mechanically. This could be a rare type combination, playstyle, or in Minior's case, its many forms. Once that's",
    //    "decided, though, I take it further by giving them balance adjustments or new forms similar to the others in the game.",
    //    "The goal with them is still variety and uniqueness, just like everything else.",
    //    "",
    //    "The game's core battle mechanics have seen some changes as well. Once again, these are primarily done to create a more",
    //    "diverse metagame by buffing weaker strategies, especially when it comes to the ice type. Despite how they may redefine the",
    //    "vanilla game in essence, they still attempt follow similar design principles, such as how the type chart changes all have",
    //    "thematic backing, and the change that makes ghost types immune to hail mirrors how there are three types immune to sandstorm."
    //],
    //[
    //    "How it is balanced",
    //    "Evaluating the balance of a Pokemon game is a monumental task with countless factors at play.",
    //    "I couldn't possibly explain how everything is balanced in this hack, and I certainly make mistakes and defy my own rules at times,",
    //    "but I do have some key factors that I always consider. While balance is not the most important aspect of the game, it is a",
    //    "key part of making the variety work. Underpowered strategies hurt variety by pushing players towards the same, more consistent",
    //    "strategies, and overpowered strategies hurt variety by rendering other strategies irrelevant if the player has access to them.",
    //    "",
    //    "First, as I mentioned before, large scale changes are first and foremost made in the interest of diversity.",
    //    "Even if a Pokemon isn't consistently strong, having unique traits that other Pokemon can't replicate ensures they can still",
    //    "be useful given the right team or player. This diversity is far more important than strength itself, which means Pokemon",
    //    "will still end up being strong or weak, but this is an inevitable result of the complexity of the game, and it's a",
    //    "much healthier dynamic anyway. Imagine a game where every Pokemon is exactly the same. It wouldn't be very fun.",
    //    "",
    //    "There are other reasons why some Pokemon should be stronger than others. One example that gets overlooked in many rom hacks",
    //    "is the progression from early to late game. Pseudolegendary dragons are much stronger than route 1 rodents and bugs.",
    //    "This is good because it gives these Pokemon a distinct portion of the game where they can excel. Rodents evolve early,",
    //    "and for the first few gyms, they are very strong compared to the unevolved Pokemon around them. Then in the mid game,",
    //    "they fall off to make room for a new group of Pokemon to be strong. I've seen many developers attempt to buff rodents",
    //    "to be strong in the mid and late game, in the process removing their identity and throwing them into the mid game",
    //    "normal archetype which already struggles to have a meaningful identity of its own. Conversely, pseudolegendaries are",
    //    "exceptionally strong, but only near the end of the game. Their strength is balanced out by the fact that they are",
    //    "very weak in the mid game compared to their competition. If they were nerfed and were allowed to evolve sooner, they",
    //    "too would lose their identity and become less interesting.",
    //    "",
    //    "Another factor to consider is player skill. This hack is meant for mid level players, where mistakes and sub-optimal",
    //    "decisions are expected. This, of course, means a lower power level is necessary to win, but it also has an effect on what",
    //    "what strategies should be strong. One design element I like to think about a lot is pushing and pulling, where an uneven",
    //    "power dynamic, as well as other factors, can incentivize players to play in the way that is most interesting.",
    //    "Permanent weather, for example, is one of the most powerful, and at times controversial, aspects of generation 5.",
    //    "I, however, really like weather because it forces the player to interact with many different aspects of the game.",
    //    "To use it effectively requires a good understanding of the game's mechanics, synergies, and team building, which leads",
    //    "to many creative and bizarre decisions like Starmie being strong on sandstorm teams despite not being immune to it.",
    //    "I want weather to be strong and have buffed it in many ways because I want to encourage players to interact with",
    //    "these mechanics more.",
    //    "",
    //    "Where I would consider a strategy to be too strong is not necessarily based on its power but based on its ease of use.",
    //    "When a strategy allows the player to win with little to no effort, it denies them the opportunity to make these",
    //    "interesting decisions, and it disincentivizes the use of other strategies that require more effort to achieve",
    //    "the same result. Pokemon like poison heal Gliscor and eviolite Porygon 2 had to be nerfed because they fit on every team",
    //    "and could handle most fights very easily. Meanwhile other Pokemon like Torterra and Hippowdon may have a greater tanking ability",
    //    "at times, but they also have more clear drawbacks that the player has to consider to use them well.",
    //    "Similarly, a Pokemon winning a major fight by itself with no setup would need to be nerfed, but a Pokemon sweeping",
    //    "a team with the help of support and utility may be fine, as the specificity and skill involved can justify its strength.",
    //    "",
    //    "One change that has been called into question on multiple occasions is the buff to ice types that gave them 3 more resistances.",
    //    "While this has had a massive effect on certain Pokemon like Mamoswine and Cryogonal, I don't believe it's overpowered on its own.",
    //    "On the contrary, I see 4 weaknesses and 4 resistances as the bare minimum in a way, putting it on par with mediocre defensive types",
    //    "like rock and grass and by no means as strong as types like fire, water, or ghost. It's just a coincidence that the three new",
    //    "resistances it got (water, flying, and dragon) are very prominent in the late game. Of course, ice is also a strong offensive type,",
    //    "but not strong enough to warrant its complete lack of defensive utility, which is why ice is considered one of the worst types in",
    //    "most games and is often seen as being detrimental on many of the Pokemon that have it. Taking neutral hits isn't always viable when",
    //    "dealing with switch ins, crit ranges, and coverage moves, which is why resistances are needed to make the ice type's offense usable",
    //    "in the first place. The result is ice becoming one of the better types for sure, but not at all spamable and not comparable to the",
    //    "best types in the game like water and steel. At its best, it gives ice types new matchups that it can easily dominate,",
    //    "but once again, this is very much still in line with the rest of the types in the game."
    //],
    //[
    //    "About the Quality of Life",
    //    "This is actually one of the main reasons I started writing this page. Some of the most common questions I receive relate to QoL features",
    //    "that appear in modern games and other rom hacks, and players taking common QoL features (or straight up hacking) and wondering why",
    //    "I don't provide them in the game myself. In a lot of cases, the simple answer is I don't want them.",
    //    "",
    //    "So called \"Quality of Life\" is perhaps the most misunderstood concept in modding communities in general, not just for Pokemon games.",
    //    "The truth is that every change to the game has subtle effects on balance, player psychology, and the pushing and pulling concepts",
    //    "I mentioned earlier, which may detract from how the game is intended to be played, and that's not including QoL that outright and",
    //    "unapologetically removes the need to interact with key features of the game.",
    //    "And before anyone retorts with \"I should let people play the way they want,\" the people who say this are going to be the same",
    //    "people who come back and say the game is bad because they didn't even try to play in the way the game was balanced around.",
    //    "There needs to be an understanding of why things are the way they are rather than assuming the worst about the design's intentions.",
    //    "",
    //    "First and foremost: infinite rare candies.",
    //    "The abundance of difficulty hacks with hard coded level caps has conditioned an alarming amount of the community to treat experience",
    //    "as a nothing mechanic that should be bypassed, leading players to, by default, hacking in and spamming rare candies to bring every Pokemon",
    //    "up to the level cap immediately. What's important here is that by adding it as a base feature, I would indirectly signal to players that",
    //    "this is the intended way to play the game, which it's not. This may work for difficulty hacks, but I view experience management",
    //    "very differently. In this hack, experience yields and level rates have been thoroughly fine tuned. Now it is very common for the player's",
    //    "whole team to get within one or two levels of the cap just by fighting every trainer, assuming they used the same team as the last gym.",
    //    "This eliminates the perceived problem of having to grind between fights almost entirely. The next question, then, is \"What about when",
    //    "you have to add an underleveled Pokemon to the team and get them caught up?\" and this has very much been considered within the design.",
    //    "",
    //    "In a nuzlocke, the most effective strategy will always be to use six Pokemon that counter the next trainer's team as much as possible.",
    //    "This, in my opinion, is a boring way to play the game because it means you never have to explore how a Pokemon works outside of its",
    //    "comfort zone. I think the most interesting way to play is by mastering a strategy and understanding how to use it successfully",
    //    "even when the odds are stacked against you. So when I say that I don't want infinite rare candies in the game, that doesn't mean",
    //    "I want players to have to grind. What it actually means is grinding is an enabler for a strategy I don't want players to use,",
    //    "and subsequently, infinite rare candies makes this strategy much more accessible. By including grinding as a barrier, it makes",
    //    "players want to keep using the same Pokemon, even when they are not the most optimal, but worse players can still train up new Pokemon",
    //    "if they need to just to get by.",
    //    "",
    //    "One use case I can see using rare candies that doesn't detract from this intended playstyle is to only use them to top off the team",
    //    "that the player was already using right before a boss, as this is a case where the grind is unavoidable. (unless you feel like using",
    //    "underleveled Pokemon, but we're way beyond arguing that at this point) I would support this use of rare candies, but let's face it,",
    //    "most players won't have that kind of restraint without me calling it out explicitly.",
    //    "",
    //    "The next big thing I want to address is damage calculators.",
    //    "Just like infinite rare candies, this is something the kaizo community popularized and now treats as an expected way to play the game,",
    //    "even though it even more directly detracts from the idea of skill expression. Let me put it simply, anyone can plug numbers into a",
    //    "calculator for hours until they come up with a riskless solution. Not everyone has a deep understanding of the game's mechanics which",
    //    "would allow them to make good decisions for themselves. The player's ability to strategize is a valuable skill that should be emphasized",
    //    "and rewarded, not standardized through the use of external tools. Like rare candies, it also contributes to a playstyle where only",
    //    "the optimal choices are made, and the player is never put in a bad position. Like I said before, this is boring. If a player",
    //    "makes a bad decision, they should feel the effects of it, but at the same time, finding a way to recover from those mistakes",
    //    "just means more opportunities to express individual skill. This is even worse for content creators, as their viewers also have to",
    //    "sit through hours of planning, and surprise roadblocks and triumphs are what make nuzlockes truly memorable.",
    //    "Luckily, damage calculators are not as ubiquitous as rare candy cheats, but the point still stands that I won't be",
    //    "providing or endorsing them, and players who are used to them should consider putting them away for this hack.",
    //    "",
    //    "Next, I want to cover the collection of modern features like nature mints, ability patches, and bottle caps, which some players",
    //    "may be looking for. In the context of a competitive pvp environment, sure, these are quality of life features, but in a nuzlocke",
    //    "environment, which a lot of the game is designed around, they actively affect game balance by circumventing randomness.",
    //    "In this case, because I want randomness to play a major role, they are not a given. Instead, assuming I think the effect is",
    //    "good at all, they are introduced as powerful but limited tools. Being able to create the \"perfect\" Pokemon is something",
    //    "I like, as it gives the player more control and room for expression, but it must have major restrictions to avoid making",
    //    "the game too easy.",
    //    "",
    //    "IV boosters are each one time use throughout the game and require some sort of side quest, forcing the player to make decisions",
    //    "about who to use them on and contributing to the idea of keeping Pokemon for the whole run. Changing natures is similar but",
    //    "comes in tiers. Getting bad natures has always been my least favorite part of nuzlockes, so I wanted to offer a fix where",
    //    "the player can choose to normalize this rng with neutral natures, but getting strong natures like Adamant and Modest is a lot",
    //    "more limited to balance out how powerful they are.",
    //    "",
    //    "Abilities, on the other hand, will not be allowed to be changed.",
    //    "Unlike natures and IVs, where there are clear good and bad values for them, abilities are generally similar in strength but are",
    //    "foundational to how a Pokemon functions. Cinccino, for example, can be a frail sweeper with skill link or a support/utility",
    //    "Pokemon with fluffy. It's as if there are mechanically two different Pokemon in one slot, but allowing the player to swap",
    //    "abilities blurs this line and may more directly lead to one ability becoming obsolete in favor of the other.",
    //    "With hidden abilities, this becomes even more problematic. Giving every Pokemon two abilities that are similar in strength",
    //    "while also being unique from eachother is already difficult. I frankly don't want to come up with a third ability for every",
    //    "Pokemon and would rather reserve the hidden ability slot for special occasions and boss battles.",
    //    "",
    //    "The most extreme case in this hack comes from the daycare, where eggs received from it will always have perfect IVs. From a",
    //    "purely mechanical perspective, this makes sense as if you can receive one egg, you can also keep receiving eggs until one of",
    //    "them has perfect IVs, and that's not fun. Within nuzlockes, though, I prefer to play with a rule where I can only ever take",
    //    "one egg out of the daycare. This, then serves the same purpose as the IV boosters by making the player pick one Pokemon",
    //    "that they want to commit to making the star of their team. When the player is allowed to take eggs out repeatedly, this becomes",
    //    "incredibly strong, which is why I recommend using house rules and not doing that if you want to avoid making the game too easy.",
    //],
    //[
    //    "Why this is important",
    //    "The key ingredient for Infinite Black 2 is replayability. In a community where hacks are designed to be one big challenge to overcome,",
    //    "it may sound self centered to say, but playing it multiple times is where this hack really shines. It doesn't matter if you win or lose,",
    //    "whether it seems too easy or you're struggling to make progress at all. The reason I keep playing and developing is to try new things.",
    //    "New Pokemon, new strategies, new mechanics, new challenge formats.",
    //    "I wanted to create an environment where there's never a shortage of new things to try, and that takes time to fully appreciate.",
    //    "",
    //    "You'll notice this page goes into a lot of detail and may come off as aggressive towards certain parts of the community, but",
    //    "it's for a good reason. Difficulty hacks have been a contentious part of the community for a while, and they hold a small selection",
    //    "of rom hacks on pedestals that warp our perception of how challenges should be designed. When I started making Infinite Black 2,",
    //    "I didn't realize I would be grouped in with them in spite of my differing design philosophies, and now I need to break away from them",
    //    "to establish my hack as something more unique. I'm hoping this can be achieved by making it clear why I make things the way they are.",
    //],
]

function SetupCategories()
{
    document.getElementById("dexBG").innerHTML = "";

    document.getElementById('dexBG').appendChild(document.createElement("br"));

    for (let s in sections)
    {
        let b = document.createElement("div");
        b.className = "ChangesSectionHeader";
        b.innerHTML = sections[s][0];
        b.style.zIndex = 1;
        document.getElementById('dexBG').append(b);

        let text = "<ul>";
        for (let s2 = 1; s2 < sections[s].length; s2++)
        {
            if (sections[s][s2].length == 0) text += "<br>";
            else text += s == 0 ? ("<li>" + sections[s][s2] + "</li>") : (sections[s][s2] + "<br>");
        }
        text += "</ui><br><br>";
        b = document.createElement("div");
        b.className = "ChangesSection";
        b.innerHTML = text;
        b.style.zIndex = 1;
        document.getElementById('dexBG').append(b);
    }
}

function OpenTab(text)
{
    
}